spring:
  application:
    name: HOTEL-SERVICE
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hoteldb
    username: postgres
    password: password
server:
  port: 8085
  error:
    includeMessage: always
